### ISSUE TITLE
Unable to open this example project - Assertion failed - EdGraphNode.h [Line: 586]

### ISSUE THREAD

**Issue by vallamost** [SneakyKittyGameDev/SKGSFExample#1]
Whenever I try using this SKG example project in UE5.3 with the SKG 5.3 plugin, the project crashes upon trying to open it. I am able to create a blank project and enable the SKG 5.3 plugin just fine.

Are there any special instructions for getting this example project to open correctly?

Is there an older 5.3 version of this example project I can try?

`Assertion failed: Result [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Engine\Classes\EdGraph\EdGraphNode.h] [Line: 586]`

![image](https://github.com/SneakyKittyGameDev/SKGSFExample/assets/25071166/57759dea-2d9b-4f2f-87ee-aa3b789e4a51)

**Comment by SneakyKittyGameDev** [comment]
Nothing special is required, it should just work. That's a crash in the
engine so I would validate your engine just in case. I recommend hopping in
the discord as it's much easier to communicate that way and this is also
the incorrect email, I guess I forgot to change the support email somewhere
lol.

**Comment by wupy36** [comment]
I just confirmed, the project works just fine on 5.3, i also tried both the plugin in the engine plugins folder and a projects plugin folder.
